### PR TITLE
Add trim_ws argument to read_delim

### PR DESCRIPTION
**Pull request by noamross**

### CODE REVIEW

**Comment by rudazhan** [comment]
I'd like to see this commit merged! `read_csv`, `read_csv2`, and `read_tsv` all have this argument and are supposed to be special cases of the general `read_delim` function. So there's not reason for `read_delim` not to have it.

**Comment by hadley** [comment]
Looks good - can you please add a bullet to news?

**Comment by noamross** [comment]
Added and squashed

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
