### PR TITLE
Fix a bug in DateTimeParser where compound formats would get parsed as

### PR DESCRIPTION
**Pull request by kmillar**
partial ISO8601 date time format.

### CODE REVIEW

**Comment by hadley** [comment]
Would you mind explaining how the patch fixes the problem?

**Comment by kmillar** [comment]
Previously there were two overloads of parse in the code: parse(bool) and parse(const std::string&)

In e.g. 
   parse("%m/%d/%y");
you have a 'const char*'

const char* can be converted to bool, and can also be converted to std::string, so either version is possible.

The rules of C++ say that the bool conversion takes precedence, which isn't what you want here.

Generally it's a good idea to only overload functions when the semantics of the function is the same no matter which overload is chosen, otherwise things like this happen.

**Comment by hadley** [comment]
Thanks - that's very useful. I really should rename `parse(bool)` to `parseISO8601()`.

Would you mind adding a bullet to NEWS describing the bug and including `(#178, @kmillar)`

**Comment by kmillar** [comment]
Your rename suggestion is a much better approach.

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
